---
- hosts: masters
  tasks:
  - name: Swarm init
    shell: docker swarm init --advertise-addr {{ inventory_hostname }}
 
  - name: Get worker token
    shell: docker swarm join-token worker -q
    register: worker_token

  - debug:
      var: worker_token

- hosts: workers
  vars:
    token: "{{ hostvars[groups['masters'][0]]['worker_token']['stdout'] }}"
    master: "{{ hostvars[groups['masters'][0]]['inventory_hostname'] }}"
  tasks:
  - name: Join Swarm Cluster
    shell: docker swarm join --token {{ token }} {{ master }}:2377
    register: worker

  - name: Show result
    debug:
      var: worker

